### ISSUE TITLE
Tamaño letra

### ISSUE THREAD

**Issue by DesireeHolowiniec** [Selik98/MeLi-Mati.K#1]
![image](https://github.com/Selik98/MercadoLiebre-Mati.K/assets/136195327/cdd976a2-3f78-4af4-8a8d-432f91ad6e76)

Agrandar el font-size de precio, descuento y nombre del producto para que no quede tan chiquito en esta media querie

**Comment by Selik98** [comment]
Solucionado! Muchas Gracias
