### ISSUE TITLE
Visualización de dos productos a partir de 361px

### ISSUE THREAD

**Issue by DesireeHolowiniec** [Selik98/MeLi-Mati.K#3]
![image](https://github.com/Selik98/MercadoLiebre-Mati.K/assets/136195327/24a7cdb8-6660-4399-8e6c-21f6463d923d)

A partir de 361px se deberían visualizar dos productos por fila

**Comment by Selik98** [comment]
Solucionado! También cambié para que a partir de 769 se vea para Desktop. Muchas Gracias
